# Generated by Django 5.1.5 on 2025-01-22 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='bots/')),
                ('path', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wins', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('chips_won', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('winner', models.CharField(max_length=50)),
                ('total_chips_exchanged', models.IntegerField(default=0)),
                ('bot1_wins', models.IntegerField(default=0)),
                ('bot2_wins', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=5)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('rounds_data', models.JSONField()),
                ('bot1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_bot1', to='poker_tournament.bot')),
                ('bot2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_bot2', to='poker_tournament.bot')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='TestBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='test_bots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(max_length=50)),
                ('winner', models.CharField(max_length=50)),
                ('total_chips_exchanged', models.IntegerField()),
                ('test_bot_wins', models.IntegerField()),
                ('opponent_wins', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('rounds_data', models.JSONField()),
                ('test_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_matches', to='poker_tournament.testbot')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('winner', models.CharField(max_length=50)),
                ('chips_exchanged', models.IntegerField()),
                ('replay_data', models.JSONField()),
                ('hole_cards', models.JSONField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='poker_tournament.match')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('match', 'round_number')},
            },
        ),
    ]
