# Generated by Django 5.1.5 on 2025-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_tournament', '0003_testbot_chips_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbot',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testbot',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testbot',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
