# Generated by Django 5.1.5 on 2025-01-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_tournament', '0004_testbot_score_testbot_total_games_testbot_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='round',
            name='winner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testbot',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testmatch',
            name='opponent_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testmatch',
            name='winner',
            field=models.CharField(max_length=255),
        ),
    ]
