# Generated by Django 5.1.5 on 2025-01-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_tournament', '0005_alter_bot_name_alter_bot_path_alter_match_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='rounds_data',
            field=models.JSONField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='round',
            name='replay_data',
            field=models.JSONField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='testmatch',
            name='rounds_data',
            field=models.JSONField(max_length=100000),
        ),
    ]
