# Generated by Django 5.1.5 on 2025-01-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_tournament', '0007_alter_bot_name_alter_bot_path_alter_match_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='file',
            field=models.FileField(max_length=5000, upload_to='bots/'),
        ),
    ]
