# Generated by Django 5.1.5 on 2025-01-26 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poker_tournament", "0010_alter_testmatch_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testmatch",
            old_name="test_bot",
            new_name="bot1",
        ),
    ]
